import argparse
import os
import re
import shutil

parser = argparse.ArgumentParser(
    description="Generate UsbPort IO ports in the top entity of the VHDL circuit."
)

parser.add_argument(
    "--directory",
    metavar="dir",
    type=str,
    default=".",
    help="directory of where UsbPort.vhd and top entity files are (default = root of script)",
)
parser.add_argument(
    "top_entity_file",
    metavar="top_entity_file",
    type=str,
    help="top entity file name (ex: counter.vhd)",
)
parser.add_argument(
    "top_entity_name",
    metavar="top_entity_name",
    type=str,
    help="top entity name (ex: counter)",
)

USB_PORT_MAP_REGEX = ":[\s|\n]*(UsbPort)[\s|\n]*PORT[\s|\n]*MAP[\s|\n]*\("
USB_PORT_MAP_LINKS = """
-- Automated Inserted code for GHDL
    inputPort_SW => inputPort_SW,
    outputPort_SW => outputPort_SW,
-- Automated Inserted code for GHDL
"""

TOP_ENTITY_REGEX = "ENTITY[\s|\n]*({})[\s|\n]*IS[\s|\n]*PORT[\s|\n]*\("
USB_PORT_COMPONENT_REGEX = "COMPONENT[\s|\n]*(UsbPort)[\s|\n]*PORT[\s|\n]*\("
USB_PORT_DECLARATION = """
-- Automated Inserted code for GHDL
    inputPort_SW : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    outputPort_SW : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
-- Automated Inserted code for GHDL
"""


args = vars(parser.parse_args())

#
# Check if UsbPort exists, if yes, "replace" with the new one (_GHDL) which has the new signals
# TODO: move UsbPort and current top entity file to a tmp dir?
dir = str(args["directory"])
full_path = dir + "/UsbPort.vhd"
file_exists = os.path.exists(full_path)
if file_exists == False:
    print("[-] File '{}' does not exist...".format(full_path))
    exit(1)

# move usbport to tmp/
if not os.path.exists(dir + "/tmp"):
    os.makedirs(dir + "/tmp")

if os.path.exists(dir + "/tmp"):
    shutil.move(full_path, dir + "/tmp")

full_path = str(dir) + "/UsbPort_GHDL.vhd"
f = open(full_path, "w")
f.write(
    """-- Auto generated by $generate_usb_ports_ghdl.py$ script.
LIBRARY ieee;
USE ieee.STD_LOGIC_1164.ALL;

ENTITY UsbPort_GHDL IS
    PORT (
        inputPort : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
        outputPort : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        inputPort_SW : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        outputPort_SW : IN STD_LOGIC_VECTOR(7 DOWNTO 0)
    );
END ENTITY;

ARCHITECTURE UsbPort OF UsbPort_GHDL IS
BEGIN
    inputPort_SW <= inputPort;
    outputPort <= outputPort_SW;
END ARCHITECTURE;
"""
)
f.close()
print("[+] {} generated!".format(full_path))

#
# Open top entity file and replace the UsbPort component declaration with UsbPort_GHDL
top_entity_file = str(args["top_entity_file"])
full_path = dir + "/" + top_entity_file
file_exists = os.path.exists(full_path)
if file_exists == False:
    print("[-] Top file entity '{}' does not exist...".format(full_path))
    exit(1)

fp = open(full_path, "r")
data = fp.read()
f.close()

# move old source to tmp/
if not os.path.exists(dir + "/tmp"):
    os.makedirs(dir + "/tmp")

if os.path.exists(dir + "/tmp"):
    shutil.move(full_path, dir + "/tmp")

match = re.search(USB_PORT_COMPONENT_REGEX, data, flags=re.S | re.I)
if match == None:
    print(
        "[-] Top file entity '{}' does not have a valid UsbPort port map instantiation...".format(
            full_path
        )
    )
    exit(1)

new_component_name = match.group(0).replace(match.group(1), "UsbPort_GHDL")
new_usb_port_component = new_component_name + USB_PORT_DECLARATION
new_data = re.sub(
    USB_PORT_COMPONENT_REGEX,
    new_usb_port_component,
    data,
    flags=re.S | re.I,
)

if data == new_data:
    print(
        "[-] Top file entity '{}' does not have a valid UsbPort component declaration...".format(
            full_path
        )
    )
    exit(1)

# Find UsbPort port map (component instantiation) and link the new signals
match = re.search(USB_PORT_MAP_REGEX, new_data, flags=re.S)
if match == None:
    print(
        "[-] Top file entity '{}' does not have a valid UsbPort port map instantiation...".format(
            full_path
        )
    )
    exit(1)

new_usb_port_name = match.group(0).replace(match.group(1), "UsbPort_GHDL")
new_port_map = new_usb_port_name + USB_PORT_MAP_LINKS
new_data = re.sub(
    USB_PORT_MAP_REGEX,
    new_port_map,
    new_data,
    flags=re.S | re.I,
)

#
# Add UsbPort ports into top entity
top_entity_name = str(args["top_entity_name"])

match = re.search(
    TOP_ENTITY_REGEX.format(top_entity_name),
    new_data,
    flags=re.S | re.I,
)
if match == None:
    print("[-] Top entity '{}' does not exist...".format(top_entity_name))
    exit(1)


new_top_entity = match.group(0) + USB_PORT_DECLARATION
new_data = re.sub(
    TOP_ENTITY_REGEX.format(top_entity_name),
    new_top_entity,
    new_data,
    flags=re.S | re.I,
)

#
# Write new generated file
full_path = dir + "/" + top_entity_file.replace(".vhd", "_generated.vhd")
fp = open(full_path, "w")
fp.write(new_data)
f.close()
